name: Packages cleanup
on: registry_package
jobs:
  clean:
    runs-on: self-hosted
    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v3
        with:
          package-name: pipeline
          min-versions-to-keep: 10
